//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiraRDKWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareHouse
    {
        public int Number { get; set; }
        public int ItemID { get; set; }
        public System.DateTime DateOfReceipt { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Item Item { get; set; }
    }
}
